// quotes/quotes.js
module.exports = [
    'The storm may roar, but it cannot drown a determined soul.',
    'Every scar you carry is proof you fought and lived.',
    'Hope is the quiet voice that whispers “try again” when the world shouts “give up.”',
    'Your pace doesn’t matter, only your direction does.',
    'Strength is not in never falling, but in rising every single time.',
    'Dreams don’t fade; people just forget to chase them.',
    'Your tears are not weakness—they water the seeds of your future.',
    'Even the smallest light can guide you through the darkest night.',
    'Pain shapes you into someone stronger than you’ve ever been.',
    'The road may be steep, but every step is still progress.',
    'You don’t need to see the end of the road to start walking.',
    'Your worth is not measured by the applause of others.',
    'Some of the strongest battles are fought in silence.',
    'Even shattered glass can still reflect the sun.',
    'Your future self is watching—don’t let them down.',
    'Courage is choosing to move forward despite the trembling in your knees.',
    'Mountains are conquered one step at a time, not all at once.',
    'You are not defined by the storms you’ve endured, but by the skies you keep chasing.',
    'Every ending is just a hidden beginning.',
    'You are stronger than the moment that tries to break you.',
    'The hardest roads often lead to the most beautiful destinations.',
    'Your scars are chapters in a story worth telling.',
    'Some dreams demand more patience than others—wait for them.',
    'It’s not over just because it feels heavy—rest, then rise.',
    'Strength is born from moments you thought you couldn’t survive.',
    'Even broken wings can learn to fly again.',
    'You are not behind—you are on your own timeline.',
    'Don’t measure your journey with someone else’s map.',
    'The most powerful growth often happens in silence.',
    'Some days survival itself is an act of courage.',
    'Your failures are proof you tried, not that you can’t.',
    'When everything seems against you, remember the tide always turns.',
    'Don’t be afraid to start over—this time you’re not starting from scratch, you’re starting from experience.',
    'The climb is worth it for the view you’ve never seen before.',
    'Even the darkest night will end, and the sun will rise again.',
    'You are stronger than the voice in your head that says you’re not.',
    'No rain, no flowers—welcome the storms that help you bloom.',
    'You’ve made it through 100% of your worst days.',
    'Let your hope be louder than your fear.',
    'Growth hurts because you are stretching into someone stronger.',
    'Your dreams are valid even if no one else understands them.',
    'Don’t let the weight of today sink the ship of tomorrow.',
    'You are allowed to rest without quitting.',
    'Every setback is a setup for a comeback.',
    'The journey matters more than the applause.',
    'Some chapters will be messy, but they are still part of your story.',
    'Your courage can be someone else’s hope.',
    'You don’t have to run; you just have to keep moving.',
    'Failure is not falling—it’s refusing to get back up.',
    'When the world says “no,” let your heart say “watch me.”',
    'Your light is needed, even if the world doesn’t say so.',
    'Some battles are meant to teach you, not defeat you.',
    'Don’t rush the process—growth takes time.',
    'Your voice matters, even if it shakes.',
    'Every sunrise is a reminder that you have another chance.',
    'You are not your mistakes; you are the lessons you’ve learned.',
    'Your presence is a gift someone is praying for.',
    'You can be both a masterpiece and a work in progress.',
    'The weight you carry will one day become your strength.',
    'Your small steps today will be giant leaps tomorrow.',
    'It’s okay to walk slowly; just don’t walk backward.',
    'Your story is still being written—don’t close the book yet.',
    'Even in the desert, flowers find a way to bloom.',
    'Your silence can be powerful when used with wisdom.',
    'You are stronger than you think, and braver than you believe.',
    'When the fire burns low, protect the ember—it’s still alive.',
    'The struggle is the price you pay for becoming unshakable.',
    'Don’t let the fear of failure steal the beauty of trying.',
    'Your resilience is your greatest treasure.',
    'Every bruise tells a story of survival.',
    'You are not meant to be understood by everyone.',
    'Even the tallest tree started as a small seed.',
    'You are worthy of the dreams you carry.',
    'Your comeback will be stronger than your setback.',
    'The rain that falls now will water tomorrow’s blessings.',
    'Your broken pieces can still build something beautiful.',
    'Don’t wait for permission to shine.',
    'You are the author of the next chapter of your life.',
    'Even in chaos, you can find your calm.',
    'The more you are tested, the stronger you become.',
    'Your worth is not dependent on your productivity.',
    'You are allowed to take up space.',
    'The person you become is worth the pain you endure.',
    'Even the longest winter eventually turns to spring.',
    'You can rebuild from the ashes and be stronger.',
    'Your heart knows the way—listen to it.',
    'You are not too late; you are right on time for your path.',
    'Your kindness is your quiet revolution.',
    'When you can’t see the way, create one.',
    'Your effort matters more than instant results.',
    'You’ve survived too much to doubt your strength now.',
    'Even if no one claps, your progress still counts.',
    'Your journey is proof that impossible things happen.',
    'You are not broken—you are becoming.',
    'Every storm you face prepares you for the next horizon.',
    'Your courage today will be your strength tomorrow.',
    'You are still here, and that means hope is still here too.',
    'Hindi lahat ng sugat ay nakikita sa balat, pero lahat ng ito ay bahagi ng ating lakas.',
    'Sa bawat patak ng ulan, may dalang aral na magpapalago sa ating mga pangarap.',
    'Ang kabiguan ay hindi ang katapusan, kundi isang pagkakataon upang matutunan kung paano tumayo muli.',
    'Ang pinakamahalaga ay hindi ang bilis ng iyong pagtakbo, kundi ang tapang mong magpatuloy.',
    'Ang tunay na lakas ay hindi nasusukat sa katawan, kundi sa tibay ng loob at pananampalataya.',
    'Kahit gaano kadilim, may mga bituin pa ring magbibigay ng liwanag sa ating daraanan.',
    'Ang bawat sugat na nararamdaman ay paalala na tayo ay buhay at may kakayahang magbago.',
    'Hindi ang opinyon ng iba ang magtatakda ng ating halaga, kundi ang ating malasakit at kabutihan.',
    'Ang mga sugat, kahit malalalim, ay may layuning magpatibay sa ating pagkatao.',
    'Ang bawat hakbang patungo sa pangarap, gaano man ito kaliit, ay hakbang pa rin patungo sa tagumpay.',
    'Kung wala kang makitang daan, magtayo ka ng sarili mong landas.',
    'Ang lakas ng loob ay hindi ang walang takot, kundi ang magpatuloy kahit ramdam mo ang takot.',
    'Walang imposible sa isang pusong may malasakit at determinasyon.',
    'Ang bawat patak ng luha ay bahagi ng ating paglago.',
    'Walang pagkatalo kung natututo kang bumangon mula sa pagkadapa.',
    'Sa gitna ng pagdapo ng unos, may mga bukas na maghihintay ng mas maliwanag.',
    'Ang lakas na nagmumula sa kahinaan ay hindi kayang maipaliwanag ng sinuman.',
    'Ang mga pagdapa ay hindi tanda ng pagkatalo, kundi ng lakas na magpatuloy.',
    'Ang mga araw na puno ng hirap ay siyang maghuhubog sa atin upang maging mas matatag.',
    'Ang tagumpay ay isang paglalakbay na puno ng sakripisyo, ngunit ito ay may malalim na kahulugan.',
    'Hindi lahat ng sugat ay kailangang itago, minsan sila ay paalala ng mga bagay na natutunan mo.',
    'Ang tagumpay ay hindi isang destinasyon, kundi isang proseso ng patuloy na pag-unlad.',
    'Walang masama sa pagtakbo ng mabagal, ang mahalaga ay tuloy-tuloy ka pa ring umaabante.',
    'Ang pinakamalaking lakas ng isang tao ay hindi ang lakas ng kanyang katawan, kundi ang lakas ng kanyang pananampalataya sa sarili.',
    'Huwag mong hayaang ang bawat pagkatalo ay magpahinto sa iyong mga pangarap.',
    'Ang buhay ay tulad ng dagat—minsan tahimik, minsan magulo, ngunit palaging may pag-asa sa dulo.',
    'Sa bawat laban, ang pinakamahalaga ay hindi ang pagiging perpekto, kundi ang pagkakaroon ng tapang na lumaban.',
    'Ang tunay na tagumpay ay hindi nakikita sa panlabas na anyo, kundi sa iyong puso at mga ginagawa.',
    'Hindi sa lahat ng pagkakataon ang tamang sagot ay malinaw, pero laging may pagkakataon upang matutunan ang tamang desisyon.',
    'Kung hindi mo kayang tumakbo, maglakad ka lang. Ang mahalaga ay hindi ang bilis, kundi ang pagtahak sa tamang landas.',
    'Kahit na walang sumusuporta, may pag-asa pa ring matatagpuan sa loob mo.',
    'Ang tunay na lakas ay nakikita hindi sa kung gaano tayo kabigat na magdala ng pasanin, kundi sa kung paano tayo bumangon mula rito.',
    'Kahit sa pinakamadilim na oras, may liwanag na naghihintay sa dulo.',
    'Ang bawat pagkakataon ng kabiguan ay pagkakataon upang matutunan ang mas magagandang aral.',
    'Ang mga sugat na dinadala natin ay hindi dahilan para mawalan ng pag-asa—sa halip, sila ay mga patunay na tayo ay nabubuhay at lumalaban.',
    'Ang tagumpay ay hindi nakasalalay sa bilis ng pag-abot sa layunin, kundi sa tibay ng puso na magpatuloy.',
    'Sa bawat hakbang na tinatahak mo, kahit mabagal, ikaw ay patuloy na lumalapit sa iyong pangarap.',
    'Huwag matakot magkamali—bawat pagkatalo ay may kabuntot na aral.',
    'Sa bawat sakit at hirap, may mga bagay na natutunan na maghuhubog sa atin upang maging mas matatag.',
    'Kahit hindi mo nakikita ang buong daan, sapat nang magsimula ka at magtiwala sa iyong kakayahan.',
    'Ang pinakamahalaga sa buhay ay hindi ang pagtatapos, kundi ang bawat hakbang na ginawa mong matapang.',
    'Sa bawat bagong umaga, may bagong pagkakataon upang magsimula at lumaban muli.',
    'Huwag mong kalimutan ang iyong pinagmulan, dahil ito ang magsisilbing gabay sa iyong pag-abot sa tagumpay.',
    'Ang lakas ng loob ay hindi sa walang takot, kundi sa tapang na magpatuloy kahit nahihirapan.',
    'Ang bawat araw ay isang pagkakataon upang maging mas mabuting tao.',
    'Kapag masakit, doon nagsisimula ang pinakamagandang bahagi ng buhay.',
    'Ang hirap ng buhay ay hindi pagwawakas, kundi bahagi ng ating paglalakbay patungo sa mas mataas na layunin.',
    'Ang pinakamalaking tagumpay ay hindi sa pagtatapos ng laban, kundi sa pagpapatawad at pagtanggap sa ating sarili.',
    'Ang tapang ay hindi pagsuko, kundi ang kakayahang magpatuloy sa kabila ng lahat ng pagsubok.',
    'Bawat araw ay isang bagong pagkakataon upang magsimula at baguhin ang ating kapalaran.',
    'Ang lakas ay hindi nasusukat sa mga bagay na nakikita ng iba, kundi sa mga bagay na pinapasan mo nang tahimik.',
    'Ang bawat pagdapo ng pagkatalo ay nagiging pagkakataon na magsimulang muli.',
    'Ang lahat ng paghihirap ay may hangganan, at sa bawat pagsubok ay may tagumpay na naghihintay.',
    'Ang tunay na tapang ay ang magpatuloy sa kabila ng mga pagdududa.',
    'Kahit na ang pinakamadilim na gabi ay lilipas din, at ang araw ay muling sisikat.',
    'Ang tunay na kahulugan ng tagumpay ay hindi ang pagdating sa dulo, kundi ang mga aral na nakuha mula sa bawat hakbang.',
    'Ang puso na puno ng pangarap ay hindi madaling mawalan ng pag-asa.',
    'Ang bawat hakbang ay mahalaga, kaya\'t huwag kang manghinayang sa bawat maliit na tagumpay.',
    'Huwag mong hayaan na ang iyong takot ang magtakda ng iyong hangganan.',
    'Sa bawat pagsubok, may pagkakataon na mas lumalakas ka.',
    'Ang lakas na tinataglay mo ngayon ay bunga ng mga bagay na pinagdadaanan mo.',
    'Ang pagtanggap sa ating mga pagkatalo ay nagsisilbing pundasyon para sa ating tagumpay.'
];
